# Generated by Django 5.0.6 on 2024-10-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0030_remove_nossahistoria_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('imagem', models.ImageField(upload_to='imagens/')),
            ],
        ),
        migrations.DeleteModel(
            name='NossaHistoria',
        ),
    ]
