# Generated by Django 5.0.6 on 2024-10-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0031_historia_delete_nossahistoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('data_publicacao', models.DateField()),
            ],
        ),
    ]
