# Generated by Django 5.0.6 on 2024-10-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0032_noticia3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_semana', models.CharField(max_length=50)),
                ('foto_cardapio', models.ImageField(upload_to='fotos_cardapio/')),
                ('nome_comida', models.CharField(max_length=100)),
                ('data_cardapio', models.DateField()),
            ],
            options={
                'verbose_name': 'Cardápio Integrado',
                'verbose_name_plural': 'Cardápios Integrados',
            },
        ),
    ]
