# Generated by Django 5.0.6 on 2024-10-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0033_integrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularLanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dia_semana', models.CharField(max_length=20)),
                ('nome_comida', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='lanche_imagens/')),
                ('data_cardapio', models.DateField()),
            ],
        ),
    ]
