# Generated by Django 5.0.6 on 2024-10-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0034_regularlanche'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularAlmoco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(max_length=10)),
                ('nome_da_comida', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('data_do_cardapio', models.DateField()),
            ],
        ),
    ]
