# Generated by Django 5.0.6 on 2024-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0035_regularalmoco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularalmoco',
            name='dia_da_semana',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
